// Which distinct outputs occurred, in which runs, how often.
//
// The interesting question about the divergence is whether the alternative outputs are drawn
// from a bounded set — which would point at a discrete race — or whether every divergent
// render is its own snowflake, which would point at drift. That question is answered by
// recurrence across runs, so the census is per-run and not pooled into a total.
//
//   node tools/digest-census.mjs > results/digest-census.md
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const RUNS = [
  ['A', 'results/measured/layer2-runA-192.tsv', 'unmutated'],
  ['B', 'results/measured/layer2-runB-192.tsv', 'unmutated'],
  ['1', 'results/this-repo/layer2-run1-192.tsv', 'unmutated'],
  ['2', 'results/this-repo/layer2-run2-192.tsv', 'unmutated'],
  ['poolB', 'results/measured/layer2-poolarmB-192.tsv', 'pool reuse disabled'],
];

const rows = RUNS.map(([id, file, arm]) => {
  const lines = readFileSync(join(ROOT, file), 'utf8').split('\n').filter((l) => /^\d+\t/.test(l));
  if (lines.length === 0) throw new Error(`VOID: ${file} parsed to zero rows`);
  const digests = lines.map((l) => l.split('\t')[3]);
  const counts = new Map();
  for (const d of digests) counts.set(d, (counts.get(d) ?? 0) + 1);
  const canonical = [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0];
  return { id, file, arm, n: digests.length, canonical, counts };
});

const canonicals = new Set(rows.map((r) => r.canonical));
if (canonicals.size !== 1) throw new Error(`runs disagree on the canonical render: ${[...canonicals].join(', ')}`);
const CANON = [...canonicals][0];

const alts = [...new Set(rows.flatMap((r) => [...r.counts.keys()]).filter((d) => d !== CANON))].sort();
const cell = (r, d) => r.counts.get(d) ?? 0;
const unmutated = rows.filter((r) => r.arm === 'unmutated');

const out = [
  '# Digest census',
  '',
  'Generated by `pnpm census`. One column per run, one row per distinct output other than the',
  'canonical render. The canonical render is the modal digest and is the same in all five runs:',
  '',
  '```',
  CANON,
  '```',
  '',
  '| digest | ' + rows.map((r) => `run ${r.id}`).join(' | ') + ' | runs |',
  '|---|' + rows.map(() => '---|').join('') + '---|',
  ...alts.map((d) => {
    const cells = rows.map((r) => cell(r, d));
    return `| \`${d.slice(0, 8)}\` | ${cells.map((c) => (c === 0 ? '·' : c)).join(' | ')} | ${cells.filter(Boolean).length} |`;
  }),
  '',
  '| | ' + rows.map((r) => `run ${r.id}`).join(' | ') + ' | |',
  '|---|' + rows.map(() => '---|').join('') + '---|',
  '| N | ' + rows.map((r) => r.n).join(' | ') + ' | |',
  '| divergent | ' + rows.map((r) => r.n - cell(r, CANON)).join(' | ') + ' | |',
  '| arm | ' + rows.map((r) => r.arm).join(' | ') + ' | |',
  '',
  '## What this shows',
  '',
  `Across the ${unmutated.length} unmutated runs (${unmutated.reduce((a, r) => a + r.n, 0)} renders) there are`,
  `**${alts.filter((d) => unmutated.some((r) => cell(r, d))).length} distinct alternative outputs** for one fully deterministic pattern.`,
  '',
  `**${alts.filter((d) => rows.filter((r) => cell(r, d)).length > 1).length} of ${alts.length} alternatives occur in more than one run**, and several recur within a`,
  'single run — `9d9c38ce` four times inside run A alone. Alternatives that recur across',
  'independent runs are what separates a discrete race with a bounded outcome set from',
  'floating-point drift, which would not repeat a digest.',
  '',
  'The set is not obviously closed: runs 1 and 2 each contributed outputs not seen before, so',
  'the honest statement is that at least this many distinct outputs exist, not that this is all',
  'of them.',
  '',
].join('\n');

writeFileSync(join(ROOT, 'results', 'digest-census.md'), out);
console.log(out);
