// `pnpm versions` — the resolved version of every package this study's claims depend on,
// read from the INSTALLED tree rather than from the manifest. A manifest states a range; a
// result was produced by exactly one version, and only the installed tree knows which.
//
// Writes results/versions.md so the file a reader diffs is generated, never hand-maintained.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { resolveDir } from './resolve-chain.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SUBJECTS = [
  ['layer1', 'layer1/package.json', ['@strudel/core'], 'the pattern engine'],
  ['layer1', 'layer1/package.json', ['@strudel/mini'], 'mini-notation parser'],
  ['layer1', 'layer1/package.json', ['@strudel/core', 'fraction.js'], 'represents EVERY layer-1 time value'],
  ['layer2', 'layer2/package.json', ['@strudel/core'], 'the pattern engine'],
  ['layer2', 'layer2/package.json', ['@strudel/mini'], 'mini-notation parser'],
  ['layer2', 'layer2/package.json', ['@strudel/webaudio'], 'supplies renderPatternAudio'],
  ['layer2', 'layer2/package.json', ['superdough'], 'the voice/scheduling layer under it'],
  ['layer2', 'layer2/package.json', ['node-web-audio-api'], 'supplies Web Audio to Node'],
  ['layer2', 'layer2/package.json', ['@strudel/core', 'fraction.js'], 'exact rationals'],
  ['layer2', 'layer2/package.json', ['@strudel/core', '@kabelsalat/web'], 'patched — see patches/'],
];

const manifests = Object.fromEntries(
  ['layer1', 'layer2'].map((p) => [p, JSON.parse(readFileSync(join(ROOT, p, 'package.json'), 'utf8')).dependencies]),
);
const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

const rows = SUBJECTS.map(([tree, from, chain, why]) => {
  const name = chain[chain.length - 1];
  let version = '(unresolved)';
  try { version = JSON.parse(readFileSync(join(resolveDir(from, chain), 'package.json'), 'utf8')).version; } catch {}
  const declared = manifests[tree][name] ?? rootPkg.pnpm.overrides?.[name] ?? '(transitive)';
  return { tree, name, declared, version, why, patched: !!rootPkg.pnpm.patchedDependencies?.[`${name}@${version}`] };
});

const w = (k, min) => Math.max(min, ...rows.map((r) => String(r[k]).length));
const cols = [['tree', 4], ['name', 7], ['declared', 8], ['version', 8], ['patched', 7], ['why', 3]];
const line = (cells) => '| ' + cells.map((c, i) => String(c).padEnd(w(cols[i][0], cols[i][1]))).join(' | ') + ' |';

const body = [
  '# Resolved versions',
  '',
  'Generated by `pnpm versions`, read from the installed tree. This is the DEFAULT tree, and',
  'every number this repository produces by default was produced by exactly these versions.',
  '`pnpm-lock.yaml` pins them; this file exists so the pinning is legible and diffable without',
  'reading a lockfile.',
  '',
  'Two published results were deliberately produced somewhere else, and neither is described',
  'by this table:',
  '',
  '- `results/layer1-strudel-126.md` — layer 1 on `@strudel/core` 1.2.6 rather than the 1.2.5',
  '  pinned below. `pnpm layer1:126` installs it, measures, and restores this tree.',
  '- `results/measured/layer1-native-linux-x64.txt` — a run on a native `linux-x64` host,',
  '  reported rather than produced here. Its own header names its Node version.',
  '',
  `Host of record: \`${process.platform}-${process.arch}\`, Node \`${process.version}\`.`,
  '',
  line(cols.map(([c]) => c)),
  '|' + cols.map(([c, m]) => '-'.repeat(w(c, m) + 2)).join('|') + '|',
  ...rows.map((r) => line([r.tree, r.name, r.declared, r.version, r.patched ? 'yes' : 'no', r.why])),
  '',
  '## Patches applied at install',
  '',
  ...Object.entries(rootPkg.pnpm.patchedDependencies ?? {}).map(([k, v]) => `- \`${k}\` <- \`${v}\``),
  '',
  'Every patch is a diff against the published package. No dependency is vendored into this',
  'repository. Everything under `patches/` other than the entry above is an experiment arm and',
  'is NOT applied by default:',
  '',
  '| patch | arm |',
  '|---|---|',
  '| `superdough@1.3.0.patch` | pool reuse disabled — layer 2, README claim 9 |',
  '| `fraction.js@5.3.4.patch` | value-preserving `n/d -> 2n/2d` — layer 1, `L1-FRAC`, must leave the digests unchanged |',
  '| `fraction.js@5.3.4.valmut-n-plus-1.patch` | changes a rational\'s VALUE. Does not produce a different digest: the run dies with `JavaScript heap out of memory`, exit 134, after about a minute |',
  '| `fraction.js@5.3.4.valmut-d-subset.patch` | the same, by a different route, with the same outcome |',
  '',
  'The two `valmut` patches are published so an observation in `layer1-normalisation.md` is',
  'reproducible, not because anyone should want to apply them. Each takes roughly a minute to',
  'reach a 4 GB heap and die — that IS the observation.',
  '',
  '## Why fraction.js is pinned',
  '',
  '`@strudel/core` declares `"fraction.js": "^5.2.1"`. That range admitted 7 published',
  'versions when this was measured (5.2.1, 5.2.2, 5.3.0–5.3.4), spanning a minor bump and',
  '2024-11-17 to 2025-08-22, on the library that represents every layer-1 time value. All 7',
  'produced identical layer-1 digests, so there is no observed divergence to report — but an',
  'unpinned range on that path would make the layer-1 claim depend on install date, so this',
  'repository pins it through `pnpm.overrides`.',
  '',
].join('\n');

writeFileSync(join(ROOT, 'results', 'versions.md'), body);
console.log(body);
